version: '3.3'
services:
  mongodb:
    image: mongo
    container_name: 'mongodb'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: subscription-sys
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin