spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

logging:
  level:
    dev.barbz: DEBUG

services:
  subscription-sys-core:
    base-url: ${env.rest.subscription-sys.base-url}
    endpoints:
      create: /v1/subscriptions/create
      retrieve-all: /v1/subscriptions
      retrieve-by-id: /v1/subscriptions/{subscriptionId}
      delete: /v1/subscriptions/{subscriptionId}/delete
