server:
  port: 8081
  error:
    whitelabel:
      enabled: false

spring:
  data:
    mongodb:
      uri: ${env.mongo.uri}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

logging:
  level:
    dev.barbz: DEBUG
