server:
  port: 8081

spring:
  data:
    mongodb:
      database: ${env.mongo.database}
      host: ${env.mongo.host}
      username: ${env.mongo.user}
      password: ${env.mongo.password}
      port: ${env.mongo.port}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

logging:
  level:
    dev.barbz: DEBUG
