server:
  port: 8081
  error:
    whitelabel:
      enabled: false

spring:
  data:
    mongodb:
      uri: ${env.mongo.uri}
  rabbitmq:
    port: ${env.rabbitmq.port}
    username: ${env.rabbitmq.user}
    password: ${env.rabbitmq.password}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

logging:
  level:
    dev.barbz: DEBUG

messaging:
  queue:
    send-mail: send-mail
