server:
  port: 8082
  error:
    whitelabel:
      enabled: false

spring:
  data:
    mongodb:
      port: ${env.mongo.port}
      host: ${env.mongo.host}
      username: ${env.mongo.username}
      password: ${env.mongo.password}
      database: ${env.mongo.database}
      authentication-database: ${env.mongo.authentication-database}
  rabbitmq:
    port: ${env.rabbitmq.port}
    username: ${env.rabbitmq.user}
    password: ${env.rabbitmq.password}
    host: ${env.rabbitmq.host}
  mail:
    host: ${env.mail.host}
    port: ${env.mail.port}
    username: ${env.mail.user}
    password: ${env.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: ${env.mail.ssl.enable}
          starttls:
            enable: ${env.mail.starttls.enable}

logging:
  level:
    dev.barbz: DEBUG

messaging:
  queue:
    send-notification-mail: send-notification-mail
