server:
  port: 8082
  error:
    whitelabel:
      enabled: false

spring:
  data:
    mongodb:
      uri: ${env.mongo.uri}
  rabbitmq:
    port: ${env.rabbitmq.port}
    username: ${env.rabbitmq.user}
    password: ${env.rabbitmq.password}
  mail:
    host: ${env.mail.host}
    port: ${env.mail.port}
    username: ${env.mail.user}
    password: ${env.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: ${env.mail.ssl.enable}
          starttls:
            enable: ${env.mail.starttls.enable}

logging:
  level:
    dev.barbz: DEBUG

messaging:
  queue:
    send-notification-mail: send-notification-mail
